# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Unique string that represents the device')),
                ('spec', models.TextField(verbose_name='Exposed operations specifications')),
                ('online', models.BooleanField(default=False, verbose_name='The online/offline state of the device')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='Last time when the device was online')),
            ],
        ),
    ]
