# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.TextField(verbose_name='Operation specification')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='spec',
        ),
        migrations.AddField(
            model_name='operation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='device.Device'),
        ),
    ]
