# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20160816_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'int', b'Integer'), (b'str', b'String'), (b'bool', b'Boolean')], max_length=32, verbose_name='Type of argument')),
                ('name', models.CharField(max_length=256, verbose_name='Argument name')),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='spec',
        ),
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of operation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Interval (in ms) at which data is published by this operation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(default='N/A', max_length=256, verbose_name='Valid (language specific) operation name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='topic',
            field=models.CharField(default='N/A', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[(b'call', b'Callable'), (b'recv', b'Data source')], default='call', max_length=32, verbose_name='Operation data direction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arg',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='args', to='device.Operation'),
        ),
    ]
