# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20160818_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='last_online',
            new_name='last_seen',
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Valid (language specific) operation name'),
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together=set([('name', 'device')]),
        ),
    ]
