# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20160829_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='interval',
        ),
    ]
